# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e10d7fd6cb6454d186ef9f18d01f2b14ca760422facab333ac78945f0166adab3296c403e6bfefadac296518aad5fa377423cfcf73cf109d0825aebf119549

test:
  secret_key_base: c8184e776b1e70a48b5b028fde52da35fea4e215c35d33bafa1363b4b2d5ed8883d418362a1822fe73f27dd302edbd27bda2fb571e64b2096c46dba476abb04d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
